import jsPDF from 'jspdf';

function getTimestampSuffix() {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');
  const hh = String(now.getHours()).padStart(2, '0');
  const min = String(now.getMinutes()).padStart(2, '0');
  return `${yyyy}${mm}${dd}-${hh}${min}`;
}

function downloadBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function extractBullets(summaryItems: string[], fallbackSummary: string) {
  if (summaryItems.length) {
    return summaryItems.map((item) => item.trim()).filter(Boolean);
  }

  return fallbackSummary
    .split('\n')
    .map((line) => line.replace(/^\s*[-•]\s*/, '').trim())
    .filter(Boolean);
}

function extractAttendees(transcript: string) {
  const speakerRegex = /^(?:\[(\d{2}:\d{2}(?::\d{2})?)\]\s*)?([^:\n]{1,80}):\s*/;
  const names = new Set<string>();

  transcript
    .split('\n')
    .map((line) => line.trim())
    .forEach((line) => {
      const match = line.match(speakerRegex);
      if (!match) return;
      const speaker = (match[2] || '').trim();
      if (!speaker) return;
      if (speaker.toLowerCase() === 'unknown') return;
      names.add(speaker);
    });

  return Array.from(names).sort((a, b) => a.localeCompare(b));
}

function drawPageHeader(doc: jsPDF, title: string) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 36;
  const headerHeight = 56;

  doc.setFillColor(26, 26, 26);
  doc.roundedRect(margin, margin, pageWidth - margin * 2, headerHeight, 10, 10, 'F');

  doc.setTextColor(235, 235, 235);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Open MeetSum', margin + 16, margin + 22);

  doc.setTextColor(205, 205, 205);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(title, margin + 16, margin + 40);

  return margin + headerHeight + 22;
}

function drawSectionTitle(doc: jsPDF, title: string, y: number) {
  doc.setTextColor(32, 32, 32);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text(title, 48, y);

  doc.setDrawColor(200, 200, 200);
  doc.line(48, y + 8, doc.internal.pageSize.getWidth() - 48, y + 8);
}

function drawPageFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setTextColor(140, 140, 140);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Generated by Open MeetSum • Page ${page} of ${pageCount}`, pageWidth / 2, pageHeight - 20, {
      align: 'center',
    });
  }
}

function formatDisplayDate(value?: Date | string | number | null) {
  if (value === null || value === undefined) return '';
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleString();
}

export function exportSummaryPdf(
  summaryItems: string[],
  fallbackSummary: string,
  transcript: string,
  meetingDate?: Date | string | number | null,
  attendeeOverrides?: string[]
) {
  const bullets = extractBullets(summaryItems, fallbackSummary);
  const attendees = (attendeeOverrides && attendeeOverrides.length)
    ? Array.from(new Set(attendeeOverrides.map((name) => String(name || '').trim()).filter(Boolean)))
        .sort((a, b) => a.localeCompare(b))
    : extractAttendees(transcript || '');
  const meetingDateLabel = formatDisplayDate(meetingDate);
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxLineWidth = doc.internal.pageSize.getWidth() - margin * 2;

  let y = drawPageHeader(doc, 'Meeting Summary Report');

  doc.setTextColor(80, 80, 80);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Meeting date: ${meetingDateLabel || 'Not available'}`, margin, y);
  y += 22;

  drawSectionTitle(doc, 'Attendees', y);
  y += 26;

  doc.setTextColor(32, 32, 32);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);

  if (!attendees.length) {
    doc.text('No labeled speakers detected.', margin, y);
    y += 20;
  } else {
    attendees.forEach((name) => {
      if (y + 16 > pageHeight - margin) {
        doc.addPage();
        y = drawPageHeader(doc, 'Meeting Summary Report');
        drawSectionTitle(doc, 'Attendees (continued)', y);
        y += 26;
        doc.setTextColor(32, 32, 32);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
      }
      doc.text(`• ${name}`, margin, y);
      y += 16;
    });
    y += 8;
  }

  if (y + 40 > pageHeight - margin) {
    doc.addPage();
    y = drawPageHeader(doc, 'Meeting Summary Report');
  }

  drawSectionTitle(doc, 'Summary Points', y);
  y += 26;

  doc.setTextColor(32, 32, 32);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);

  if (!bullets.length) {
    doc.text('No summary points available.', margin, y);
  } else {
    bullets.forEach((bullet, index) => {
      const wrapped = doc.splitTextToSize(`${index + 1}. ${bullet}`, maxLineWidth);
      const requiredHeight = wrapped.length * 16;
      if (y + requiredHeight > pageHeight - margin) {
        doc.addPage();
        y = drawPageHeader(doc, 'Meeting Summary Report');
        drawSectionTitle(doc, 'Summary Points (continued)', y);
        y += 26;
        doc.setTextColor(32, 32, 32);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
      }
      doc.text(wrapped, margin, y);
      y += requiredHeight + 4;
    });
  }

  drawPageFooter(doc);

  doc.save(`meetingsum-summary-${getTimestampSuffix()}.pdf`);
}

export function exportTranscriptTxt(transcript: string) {
  const normalized = (transcript || '').trim() || 'No transcript available.';
  const blob = new Blob([normalized], { type: 'text/plain;charset=utf-8' });
  downloadBlob(blob, `meetingsum-transcript-${getTimestampSuffix()}.txt`);
}
